In [1]:
import numpy as np

In [2]:
arr = np.array([3,2,4,1])
arr

array([3, 2, 4, 1])

In [3]:
arr.shape

(4,)

In [4]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr_2d.shape

(3, 3)

In [6]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])   # you can use double paranthesis or doble square bracket in 2d arrays
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(arr_2d)

numpy.ndarray

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros([5,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [19]:
np.full([6,6],15)

array([[15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15]])

In [20]:
np.full([6,3],15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15],
       [15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [21]:
np.linspace(2,10,3)

array([ 2.,  6., 10.])

In [22]:
np.linspace(3,18,1000)

array([ 3.        ,  3.01501502,  3.03003003,  3.04504505,  3.06006006,
        3.07507508,  3.09009009,  3.10510511,  3.12012012,  3.13513514,
        3.15015015,  3.16516517,  3.18018018,  3.1951952 ,  3.21021021,
        3.22522523,  3.24024024,  3.25525526,  3.27027027,  3.28528529,
        3.3003003 ,  3.31531532,  3.33033033,  3.34534535,  3.36036036,
        3.37537538,  3.39039039,  3.40540541,  3.42042042,  3.43543544,
        3.45045045,  3.46546547,  3.48048048,  3.4954955 ,  3.51051051,
        3.52552553,  3.54054054,  3.55555556,  3.57057057,  3.58558559,
        3.6006006 ,  3.61561562,  3.63063063,  3.64564565,  3.66066066,
        3.67567568,  3.69069069,  3.70570571,  3.72072072,  3.73573574,
        3.75075075,  3.76576577,  3.78078078,  3.7957958 ,  3.81081081,
        3.82582583,  3.84084084,  3.85585586,  3.87087087,  3.88588589,
        3.9009009 ,  3.91591592,  3.93093093,  3.94594595,  3.96096096,
        3.97597598,  3.99099099,  4.00600601,  4.02102102,  4.03

In [23]:
np.arange(2,25)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [24]:
np.arange(12,45,3)

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [25]:
np.random.rand()

0.4279298285036982

In [26]:
np.random.rand(3,4)             # rand fn gives values between (0,1)

array([[0.99948395, 0.58964573, 0.98538505, 0.02969979],
       [0.26146028, 0.57279191, 0.99064132, 0.24893236],
       [0.61570962, 0.00302805, 0.16361736, 0.41241415]])

In [27]:
np.random.rand(3,4,2)      

array([[[0.70716419, 0.41280278],
        [0.84485474, 0.597591  ],
        [0.21199934, 0.62894277],
        [0.73933689, 0.41144139]],

       [[0.75957492, 0.78552377],
        [0.59635423, 0.71387512],
        [0.84996639, 0.71190203],
        [0.72979801, 0.26734367]],

       [[0.63313173, 0.98469185],
        [0.0985438 , 0.71096532],
        [0.87860512, 0.32129746],
        [0.71713087, 0.24791427]]])

In [28]:
np.random.randn()

1.0198850494590355

In [29]:
np.random.randn(4)

array([-1.60496971, -0.24765246,  0.54515686, -0.67374634])

In [30]:
np.random.randn(3,3)

array([[-1.54156517, -0.02089745,  0.31310275],
       [-0.65266473,  0.88181704, -0.30328167],
       [-1.04374119, -0.18214076, -1.07279291]])

In [31]:
np.random.randn(3,2,1)                       # (0ccurence, row, column) = (3,2,1)

array([[[ 0.79376576],
        [ 1.68253125]],

       [[-0.89727911],
        [-0.04483193]],

       [[-1.02484321],
        [-0.09565765]]])

In [32]:
np.random.randint(4)

3

In [33]:
np.random.randint(4,30,31)

array([18, 22,  9, 27, 21, 14, 23, 25, 29,  8, 17, 18,  8, 20,  5, 28, 22,
       28,  6, 10, 25, 10,  9, 27, 14, 26, 14, 12,  8, 17, 11])

In [34]:
y = np.eye(10)
y

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
y.reshape(25,4)

array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [36]:
y.reshape(25,4).shape

(25, 4)

In [37]:
n1 = np.array([[1,5,7],[6,3,8]])
n2 = np.array([[2,10,9],[11,15,23]])

In [38]:
n1

array([[1, 5, 7],
       [6, 3, 8]])

In [39]:
n2

array([[ 2, 10,  9],
       [11, 15, 23]])

In [40]:
np.vstack((n1,n2))

array([[ 1,  5,  7],
       [ 6,  3,  8],
       [ 2, 10,  9],
       [11, 15, 23]])

In [41]:
np.vstack((n2,n1))

array([[ 2, 10,  9],
       [11, 15, 23],
       [ 1,  5,  7],
       [ 6,  3,  8]])

In [42]:
np.hstack((n1,n2))

array([[ 1,  5,  7,  2, 10,  9],
       [ 6,  3,  8, 11, 15, 23]])

In [43]:
np.column_stack((n1,n2))

array([[ 1,  5,  7,  2, 10,  9],
       [ 6,  3,  8, 11, 15, 23]])

In [44]:
n3 = np.array([2,3,4,5,9])
n4 = np.array([5,9,8,4,10])
np.column_stack((n3,n4))

array([[ 2,  5],
       [ 3,  9],
       [ 4,  8],
       [ 5,  4],
       [ 9, 10]])

In [45]:
np.intersect1d(n3,n4)              # Here single paranthesis is used but in stacking 2 parathesis is used

array([4, 5, 9])

In [46]:
np.setdiff1d(n3,n4)

array([2, 3])

In [47]:
n3 = np.array([2,3,4,5,9])
n4 = np.array([5,9,8,4,10])

In [48]:
np.sum([n3,n4])

59

In [49]:
np.sum([n3,n4],axis =0)                  #adds column wise

array([ 7, 12, 12,  9, 19])

In [50]:
np.sum([n3,n4],axis =1)                 # adds row wise

array([23, 36])

In [51]:
                                            # Mathematics

In [52]:
n3

array([2, 3, 4, 5, 9])

In [53]:
n3+1

array([ 3,  4,  5,  6, 10])

In [54]:
n3-1

array([1, 2, 3, 4, 8])

In [55]:
n3*2

array([ 4,  6,  8, 10, 18])

In [56]:
n3*n3

array([ 4,  9, 16, 25, 81])

In [57]:
n3/2

array([1. , 1.5, 2. , 2.5, 4.5])

In [58]:
n3.min()

2

In [59]:
np.min(n3)                     # you can use both this way to find minimum value

2

In [60]:
n3.max()

9

In [61]:
n3.argmin()

0

In [62]:
n3.argmax()

4

In [63]:
n3.mean()

4.6

In [64]:
np.mean(n3)

4.6

In [65]:
np.median(n3)

4.0

In [66]:
np.std(n3)

2.4166091947189146

# Array Indexing & Slicing

In [67]:
arr = np.array([1,4,2,5,4])
arr

array([1, 4, 2, 5, 4])

In [68]:
arr[2:4]

array([2, 5])

In [69]:
arr[:3]

array([1, 4, 2])

In [70]:
arr[1:]

array([4, 2, 5, 4])

In [71]:
arr[:]

array([1, 4, 2, 5, 4])

In [72]:
arr

array([1, 4, 2, 5, 4])

In [78]:
arr[1:5:2]                             # slicing using step as 2

array([4, 5])

In [82]:
arr[-4:-1]

array([4, 2, 5])

In [95]:
arr_2d = np.arange(0,25).reshape(5,5)

In [96]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
arr_2d[2][1]              # Indexing

11

In [98]:
arr_2d[2,1]

11

In [99]:
arr_2d[1,0:4]

array([5, 6, 7, 8])

In [100]:
arr_2d[2:4,1:5]

array([[11, 12, 13, 14],
       [16, 17, 18, 19]])

In [101]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [102]:
arr_2d.transpose()                  #Transpose of matrix

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

# Broadcasting

In [104]:
x = np.array([5,4,7,9,1])
y = [2]

In [109]:
z= x+y
z

array([ 7,  6,  9, 11,  3])

In [111]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
b = [1]

In [117]:
c = a+b
c

array([[2, 3, 4],
       [5, 6, 7]])

In [122]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d = [10,20,30]

In [123]:
a+d

array([[11, 22, 33],
       [14, 25, 36]])

In [128]:
ar = np.arange(3,20)
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [129]:
new_array = ar[np.array([5,9,2,3])]                   # index using array

In [130]:
new_array

array([ 8, 12,  5,  6])

In [139]:
p = np.array([[1,2,3], [4,5,6],[7,8,9]])
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
p[[0,1,2], [2,0,2]]                              # purely integer indexing

array([3, 4, 9])

In [145]:
# Boolean array indexing

In [146]:
a = np.arange(20)

In [147]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [148]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [149]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [150]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [151]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Numpy Operation

In [152]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [153]:
a*a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [154]:
a/a

<ipython-input-154-18210b5178b0>:1: RuntimeWarning: invalid value encountered in true_divide
  a/a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [155]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [156]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [157]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [158]:
np.max(a)

19

In [159]:
np.min(a)

0

In [160]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [161]:
np.log(a)

<ipython-input-161-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [163]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

# Thank you